name: Mirror to Deuxfleurs

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to Forgejo
        run: |
          git remote add deuxfleurs https://${{ secrets.DEUXFLEURS_USERNAME }}:${{ secrets.DEUXFLEURS_TOKEN }}@git.deuxfleurs.fr/Xstoudi/mechanic.git
          git push --mirror deuxfleurs